### PR TITLE
Added the ability to set different paths

### PR DESCRIPTION
**Pull request by bonchondev**
Hi! Really enjoy using this project, wanted to make it a little more flexible for specifying the path where you want the starter to go. Updated the README and ran tests. Please let me know if there's anything you'd like me to fix or if the approach I took doesn't fit what you'd like. Thank you!

### CODE REVIEW

**Comment by bonchondev** [comment]
Hi @sfermigier sorry to bother, just wondering if you had a chance to see this

**Comment by sfermigier** [comment]
Sorry I was on vacation ad forgot to bookmark it. I will look at it this week-end.

**Comment by bonchondev** [comment]
Hi @sfermigier, sorry to keep pinging you, just checking if I did too many changes at once or if there's something I did incorrectly for this PR?

**Comment by bonchondev** [comment]
thank you!

**Pull request merged**
